### ISSUE TITLE
Rethink contents of board.pins

### ISSUE THREAD

**Issue by ramalho** [garoa/pingo#14]
It is actually not useful to list *all* the pins together (particularly not the Vdd and Gnd pins).

Perhaps we should have several attributes or methods to list the pins:

- list only digital pins
- list only analog pins
- list all pins

(this issue is the result of observing users playing with pingo interactively)

**Comment by Vido** [comment]
@danilobellini and @ramalho,
Thanks for your suggestion.

We have this function selection with the Board.filter_pins
This came on this (quite old) commit 55339e63941d9c5827c98e52171c2d3fe6b71dec

```
digital_subset = self.board.filter_pins(pingo.DigitalPin)
```
